### ISSUE TITLE
using ~/.envwarden wise?

### ISSUE THREAD

**Issue by jalbstmeijer** [envwarden/envwarden#3]
Hi,

I assume this functionality is there for easiness and or automation.

I believe it's essential with any secrets vault it never gets stored decrypted on a file system.
But when you have an encrypted vault with the plain text master password stored together on a file system, you end up at that point.

Unintended inclusion of these files in backups or on remote servers where you have no 100% guarantee you are the only one being able to access the underlying storage could be a risk.  

Would it not be better to rely on the login/unlocked state of the parent shell?
Ideally only in login state (lock vault immediate after login in) and in an unlocked state when you want to mimic the .envwarden behavior?

Gr, J

**Comment by gingerlime** [comment]
It's a trade-off, and I think users understand it well. AWS does the same thing with their CLI and I imagine lots of other tools.

In addition:

* Nobody's forcing you to place your credentials. If you don't want to use it, don't.
* The `.envwarden` file can include just an email, not necessarily the full credentials.
* You can and should create separate Bitwarden users with limited access only to the secretss they need. That's up to the user as well.
* If you prefer to trade availability (if the system reboots, it can continue to operate) over confidentiality, then `.envwarden` allows you to do it.

So I'm inclined to keep it. Perhaps the trade-offs can be explained on some Wiki page? but I think typical users of envwarden should be familiar with this already. There's nothing new here.

**Comment by jalbstmeijer** [comment]
> * Nobody's forcing you to place your credentials. If you don't want to use it, don't.

True, but printing it on execution prominently every time suggests it's the recommended way to go.
I would suggest to leave it for the help function and doc to point to that option than.

> * The `.envwarden` file can include just an email, not necessarily the full credentials.

That's handy, did not realize that.
You might even want to be able to set the preferred Bitwarden endpoint/server in the future.

> * If you prefer to trade availability (if the system reboots, it can continue to operate) over confidentiality, then `.envwarden` allows you to do it.

I get the impression this is the use case difference between us.
In my use case I use the bw client, enwarden en browser plugin in a similar way.
They help me with my daily manual tasks in which I need to be able to easily access my credentials on demand. I always use a YubiKey to login.

Can you explain the use case in which you need permanent, persistent non interactive access to your secrets?  This will help me to not suggest things that conflict with that use case.

**Comment by gingerlime** [comment]
> True, but printing it on execution prominently every time suggests it's the recommended way to go.
> I would suggest to leave it for the help function and doc to point to that option than.

I don't think so. It's simply indicating that the file wasn't found, and highlight this as an option.

> I get the impression this is the use case difference between us.
> In my use case I use the bw client, enwarden en browser plugin in a similar way.
> They help me with my daily manual tasks in which I need to be able to easily access my credentials on demand. I always use a YubiKey to login.
> 
> Can you explain the use case in which you need permanent, persistent non interactive access to your secrets? This will help me to not suggest things that conflict with that use case.

Yes, I think your use-case is different from the stated goals of envwarden actually. These are stated in the [tagline](https://github.com/envwarden/envwarden#envwarden):

>  Manage your server secrets with Bitwarden 

So the primary use-case for envwarden, and the reason I created it, is to let you use secrets on a typically unattended, non-interactive environment (servers). 

It sounds like your use case is just to simplify fetching things from the `bw cli`? Of course, it's a totally ok use-case, but not what my primary goal for envwarden at the moment.

**Comment by jalbstmeijer** [comment]
Yes, I think I will not try to merge my changes anymore as the use cases are too different indeed.

**Comment by gingerlime** [comment]
Closing this one for now.
